login_page/urls.py
from django.conf.urls import url
from .views import index, profile, login_page, passing_login
from .custom_auth import auth_login, auth_logout

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^login_mahasiswa/$', login_page, name='login_page'),
    url(r'^passing_login/$', passing_login, name='passing_login'),
    url(r'^profile/$', profile, name='profile'),
	
	# custom auth
    url(r'^custom_auth/login/$', auth_login, name='auth_login'),
    url(r'^custom_auth/logout/$', auth_logout, name='auth_logout'),
	
]

status/urls.py
from django.conf.urls import url
from .views import index, update_status_todo, remove_todo
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^update_status_todo', update_status_todo, name='update_status_todo'),
	url(r'^remove_todo', remove_todo, name='remove_todo'),
]

tugas2/urls.py
from django.conf.urls import url , include
from django.contrib import admin
from django.views.generic import RedirectView
import login_page.urls as login_page
import tugas2_mahasiswa.urls as tugas2_mahasiswa
import tugas2_riwayat.urls as tugas2_riwayat
import tugas2_profile.urls as tugas2_profile
import tugas2_teman.urls as tugas2_teman

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', RedirectView.as_view(url='home/', permanent=True), name='index'),
    url(r'^home/', include(login_page,namespace='login_page')),
    url(r'^mahasiswa/', include(tugas2_mahasiswa,namespace='tugas2-mahasiswa')),
    url(r'^tugas2-riwayat/', include(tugas2_riwayat, namespace='tugas2-riwayat')),
    url(r'^tugas2-profile/', include(tugas2_profile, namespace='tugas2-profile')),
    #url(r'^profile/edit/', include(tugas2_profile, namespace='profile/edit')),

]

templates/session/login.html
{% extends "layout/base.html" %}
{% block content %}
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="rata-tengah">
            <div class="judul">
                <h1> Halaman Login </h1>
                <p class="text-info"> Gunakan <b> akun SSO </b> untuk login </p>
            </div>
            <form action="{% url 'lab-9:auth_login' %}" method="POST">
                {% csrf_token %}
                <p>
                    <label for="username"> Your username </label>
                    <input type="text" id="username" name="username" required>
                </p>
                <p>
                    <label for="password"> Your password </label>
                    <input type="password" id="password" name="password" required>
                </p>
                <input type="submit" class="btn btn-primary">
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/session/profile.html
{% extends "layout/base.html" %}
{% block style %}
<style type="text/css">
    .clearfix {
        overflow: auto;
    }

    #prof_pic {
        float: left;
        clear: both;
    }

    .details {
        padding: 15px 15px 15px 15px;
    }

    .details > .text {
        clear: both;
    }
</style>
{% endblock %}

{% block content %}
<!-- Content Here -->
<br>
<div class="panel panel-default">
    <div class="panel-heading">
        <h3 style="display: inline;"> Selamat datang, {{ author }} </h3>
    </div>
    <div class="panel-body" style="">
         <div class="clearfix">
            <div id="prof_pic">
                <img src="http://jscraftcamp.org/img/nophoto.png"></img>
            </div>
            <div class="clearfix details">
                <div class="clearfix details text">
                    <p> Username : {{ author }} </p>
                    <p> NPM : {{ kode_identitas }} </p>
                    <p> Role : {{ role }} </p>
                    {% if connected %}
                    <a href="{% url 'login_page:auth_logout' %}" class="btn btn-danger pull-left" onclick="return confirm('Keluar?')">
                        Logout </a>
                    {% else %}
                    <a href="{% url 'login_page:login_page' %}" class="btn btn-info" style="float: left; width: 130px">
                        Login Mahasiswa </a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>

<div>
    {% block section %}

    {% endblock %}
</div>

{% endblock %}